### ISSUE TITLE
Add support for api headers

### ISSUE THREAD

**Issue by bbpennel** [fcrepo4-exts/fcrepo-java-client#11]
Currently the client doesn't provide a way to add the following allowed headers:
* Content-Disposition
* Content-Type
* digest
* slug
* if-match
* if-none-match
* if-unmodified-since
* if-modified-since
* Range

I would like to add support for all of the headers expected for basic object creation or retrieval.

In terms of implementation, the approach so far has been additional parameters to the post/put/get/patch methods, which may get unwieldy with the full set of options.  I would favor a method override of the form:

```java
public FcrepoResponse post(final URI url, final InputStream body, final Map headers)
```

Possibly with restrictions in each method so that it can only set allowed headers, but that may be iffy since some methods cover multiple endpoints with different headers allowed.

I'm not all that informed about camel, but I believe this would work there too?

**Comment by acoburn** [comment]
This suggestion certainly works for me. Another possibility would be to use a more fluent-style interface for adding headers.

**Comment by ajs6f** [comment]
@awoods Do issues from `-exts` projects go over into Jira?

**Comment by awoods** [comment]
That is preferred.

**Comment by bbpennel** [comment]
@acoburn fluent style would be fine with me as well, but it seemed like a larger refactoring.  If this is the time for larger changes before it impacts too many clients, then I am fine with that.  Some options:

```java
// post a new file
try (FcrepoClient client = new FcrepoClient(user, pass, authHost, exceptOnFail)) {
    client.post(url).contentType(ct).digest(checksum).contentDisposition(cd)
        .body(stream).transaction(txId).perform();
}
```
or maybe?
```java

try (FcrepoClient client = FcrepoClient.createClient()) {
    // Setup authentication and a transaction
    client.authenticate(user, pass, authHost).exceptionOnFailure(true)
        .startTransaction();

    client.post(url).contentType(ct).digest(checksum).contentDisposition(cd)
        .body(stream).transaction(txId).perform();

    // New verson of an object, fcr:versions endpoint added if needed
    client.newVersion(url, slug);

    client.commit();

    client.get(url).accept("text/turtle").perform();
}
```
or generic:
```java
// post a new file
client.request().contentType(ct).digest(checksum).contentDisposition(cd)
    .body(stream).post(url);
```

Feel free to ignore the transaction or other fedora specific bits if people would rather not bring that into the client.

**Comment by bbpennel** [comment]
@acoburn True, I guess that part was overly optimistic.  I'd be interested to know how you or others feel about any of these approaches, and the header map versus fluent options.

**Comment by ajs6f** [comment]
The header map is simple, extensible, and will work, but it doesn't offer much help to the person who wants to accomplish something, but doesn't know how to encode it in HTTP headers. The fluent builder is harder to do and has to be done carefully to be extensible (i.e. `Builder<SelfType extends Builder<SelfType>>`, but is really helpful for the user. IDE autocomplete will explain what the client can do and how to do it.

What's worth the time and how much? That depends on who is working on this project. Incidentally, @bbpennel , let's take this to the [Jira ticket](https://jira.duraspace.org/browse/FCREPO-2037), okay?

**Comment by bbpennel** [comment]
Here's a WIP branch of just a post request showing the direction I'm currently going with the client, just want to make sure this is what people want before filling out the rest of it:

https://github.com/bbpennel/fcrepo-java-client/compare/master...bbpennel:fluent-wip

**Comment by awoods** [comment]
@acoburn, @mikedurbin, thoughts on @bbpennel's draft: https://github.com/bbpennel/fcrepo-java-client/compare/master...bbpennel:fluent-wip

**Comment by ajs6f** [comment]
See also the [Jira ticket](https://jira.duraspace.org/browse/FCREPO-2037).
