### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by acoburn** [fcrepo4-exts/fcrepo-java-client#2]
Once #1 is merged, I would like there to be a new release of the fcrepo-java-client. The current release version is 0.1.0, and the next release should be 0.1.1. I am happy to manage the release itself.

@mikedurbin, @daniel-dgi, as project maintainers, do you have any thoughts on this? +1 if you agree, -1 if not.

**Comment by awoods** [comment]
:+1: ...pending merge of https://github.com/fcrepo4-exts/fcrepo-java-client/pull/1

**Comment by acoburn** [comment]
0.1.1 Release is complete.
