### ISSUE TITLE
Connection management responsiblities of FcrepoClient are unclear

### ISSUE THREAD

**Issue by emetsger** [fcrepo4-exts/fcrepo-java-client#5]
It is unclear whom is responsible for managing HTTP connections that are created by the FcrepoClient on behalf of the user.  Presumably the FcrepoClient is, but in my environment I'm running across the following issues:

1. Connections are only released if the user of FcrepoClient reads the response body.  Eventually the FcrepoClient will block waiting for a free connection.
2. If an FcrepoOperationFailedException is thrown, the user of FcrepoClient has no access to the response body, and cannot free the connection.  Eventually the FcrepoClient will block waiting for free connections.

A PR demonstrating the issue follows.

**Comment by awoods** [comment]
Tracking with: https://jira.duraspace.org/browse/FCREPO-1875

**Comment by awoods** [comment]
See: https://github.com/fcrepo4-exts/fcrepo-java-client/pull/6

**Comment by acoburn** [comment]
Closing this issue as it appears to have been addressed with #7
